### PR TITLE
Feature #1 revisit

### LINKED ISSUE #1: Hard to cancel when there is no loadshedding
If there is power to the PC, but the schedule and loadshedding status indicates that there shouldn't be, your PC will powerdown/hibernate as soon as you switch it on.

A temporary fix is to disable the internet (and therefore the checking of the loadshedding status) before starting up the PC.

### PR DESCRIPTION
**Pull request by knoffelcut**
This is a reimplementation of the functionality originally build in the [feature-#1](https://github.com/m3h/loadshedding/tree/feature-%231) branch, that is
"
Implement RAN CHECK as proposed fix https://github.com/m3h/loadshedding/issues/1

Logic is similar to that originally proposed by m3h at
https://github.com/m3h/loadshedding/issues/1#issuecomment-952217448
The logic proposed by
https://github.com/m3h/loadshedding/issues/1#issuecomment-955242663
would be too difficult to implement without a refactor or code
duplication.
"

However, this functionality is build on branch [feature-#1-revisit](https://github.com/m3h/loadshedding/tree/feature-%231-revisit) and should only be merged if [pull request 17](https://github.com/m3h/loadshedding/pull/17) is accepted.

This reimplementation also addresses another concern:
"
 Ensure overlap between blocks for ran check

Ran check may have mistakenly blocked the command from running
if the script is only run in a subsequent block
E.g. this script turned the device off at night,
and the user only turned the device on again during a subsequent block,
in the morning,
previously, in this case,
the ran check would block the command from running
"

### CODE REVIEW

**Comment by knoffelcut** [comment]
Don't accept PR yet:
1. I should be able live test this functionality shortly, and I want to wait for this event
2. There is an issue with the log file names and rotation I want to sort first

**Comment by knoffelcut** [comment]
The little bout of loadshedding last week have allowed me to test this live. It seems to work well and it can be merged.

**Comment by m3h** [comment]
> The little bout of loadshedding last week have allowed me to test this live. It seems to work well and it can be merged.

I seem to have missed this. But found it now

**Review by m3h — COMMENTED** [review]
LGTM

**Review by m3h — APPROVED** [review]

**Pull request merged**
